#!/usr/bin/env bash
# GENERATED by packages/harden (pnpm --filter @korin/harden render). Do not edit by hand.
# Vultr "Startup Script" (cloud-init): free abuse/flood hardening for the korin.pink box.
# Volumetric L3/4 DDoS still needs upstream scrubbing — see docs/deploy/vps.md.
set -euo pipefail

# REQUIRED: lock SSH to your admin IP. Leaving 0.0.0.0/0 exposes SSH to the world.
SSH_ALLOW_CIDR="${SSH_ALLOW_CIDR:-0.0.0.0/0}"
# Flip to "true" only once Ergo is live, then re-run, to open the IRC ports.
IRC_ENABLED="${IRC_ENABLED:-false}"

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y docker.io docker-compose-v2 ufw fail2ban netfilter-persistent iptables-persistent

# ── Host firewall (ufw) ─────────────────────────────────────────────────────
# NOTE: Docker-published ports BYPASS ufw — the IRC ports are filtered in the
# DOCKER-USER chain below, not here.
ufw default deny incoming
ufw default allow outgoing
ufw allow from "${SSH_ALLOW_CIDR}" to any port 22 proto tcp
ufw allow 80/tcp
ufw allow 443
ufw --force enable

# ── Kernel hardening (small SYN-flood resistance) ───────────────────────────
cat >/etc/sysctl.d/99-korin-harden.conf <<'SYSCTL'
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 4096
net.core.somaxconn = 1024
net.ipv4.conf.all.rp_filter = 1
SYSCTL
sysctl --system

# ── SSH lockdown (key-only) ─────────────────────────────────────────────────
sed -i 's/^#\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#\?PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config
systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || true

# ── DOCKER-USER perimeter (the real filter for published IRC ports) ─────────
# Flush first: the chain ships with a default "-j RETURN", so appended DROPs
# would never be reached otherwise.
iptables -F DOCKER-USER 2>/dev/null || true
iptables -A DOCKER-USER -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN
iptables -A DOCKER-USER -j DROP
netfilter-persistent save || true

# ── fail2ban (SSH + Ergo) ───────────────────────────────────────────────────
cat >/etc/fail2ban/jail.d/korin.local <<'JAIL'
[sshd]
enabled = true
maxretry = 4
bantime = 1h

[ergo]
enabled  = true
filter   = ergo
# Ergo must log to this file (see packages/irc/ergo.yaml logging: method file).
logpath  = /opt/korin.pink/infra/ergo-data/ergo.log
maxretry = 6
findtime = 5m
bantime  = 1h
JAIL
systemctl enable --now fail2ban
systemctl restart fail2ban || true

echo "[korin] hardening applied. IRC_ENABLED=${IRC_ENABLED}. Re-run with IRC_ENABLED=true after Ergo is live."
