#!/usr/bin/env bash
# GENERATED by packages/harden (pnpm --filter @korin/harden render). Do not edit by hand.
# Vultr "Startup Script" (Boot Script): free abuse/flood hardening for korin.pink.
# Self-contained - does not require the repo to be cloned. Idempotent; safe to re-run.
# Volumetric L3/4 DDoS still needs upstream scrubbing - see docs/deploy/vps.md.
set -euo pipefail

# REQUIRED: lock SSH to your admin IP. Leaving 0.0.0.0/0 exposes SSH to the world.
# Vultr Boot Scripts do not inject env vars - set these inline before deploying.
SSH_ALLOW_CIDR="${SSH_ALLOW_CIDR:-0.0.0.0/0}"
# Flip to "true" once Ergo is live, then re-run, to open + rate-limit the IRC ports.
IRC_ENABLED="${IRC_ENABLED:-false}"

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y docker.io docker-compose-v2 ufw fail2ban

# -- Host firewall (ufw) -----------------------------------------------------
# NOTE: Docker-published ports BYPASS ufw - the IRC ports are filtered in the
# DOCKER-USER chain below, not here.
ufw default deny incoming
ufw default allow outgoing
ufw allow from "${SSH_ALLOW_CIDR}" to any port 22 proto tcp
# Cloud images ship a default "22/tcp ALLOW Anywhere" (or "OpenSSH") rule that
# leaves SSH world-open. Remove it AFTER the admin-CIDR allow above, so the box
# is never momentarily unreachable - only the admin source can reach 22.
ufw delete allow 22/tcp 2>/dev/null || true
ufw delete allow OpenSSH 2>/dev/null || true
ufw allow 80/tcp
ufw allow 443
ufw --force enable

# -- Kernel hardening (small SYN-flood resistance) ---------------------------
cat >/etc/sysctl.d/99-korin-harden.conf <<'SYSCTL'
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 4096
net.core.somaxconn = 1024
net.ipv4.conf.all.rp_filter = 1
# Swap is headroom for the 1 GB box, not a hot path: prefer RAM, swap late.
vm.swappiness = 10
SYSCTL
sysctl --system

# -- Swap (headroom for the 1 GB box; api + bridge + ergo can spike together) -
# Idempotent: only provision if /swapfile isn't already active. fallocate first,
# dd fallback for filesystems where fallocate can't make a swap-eligible file.
if ! swapon --show=NAME --noheadings 2>/dev/null | grep -q '/swapfile'; then
  fallocate -l 2G /swapfile || dd if=/dev/zero of=/swapfile bs=1M count=2048
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  grep -q '^/swapfile ' /etc/fstab || echo '/swapfile none swap sw 0 0' >>/etc/fstab
fi

# -- SSH lockdown (key-only) - make sure your key is attached at deploy! ------
# A sed on /etc/ssh/sshd_config loses to /etc/ssh/sshd_config.d/50-cloud-init.conf
# (drop-ins win, and cloud-init re-enables password auth). A 00- drop-in sorts
# first, so its directives take precedence over every later drop-in.
cat >/etc/ssh/sshd_config.d/00-korin-harden.conf <<'SSHD'
PasswordAuthentication no
PermitRootLogin prohibit-password
SSHD
systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || true

# -- DOCKER-USER perimeter (the real filter for published IRC ports) ---------
# Docker RECREATES (and empties) the DOCKER-USER chain every daemon start, so the
# rules must be re-applied on boot. We can't use netfilter-persistent (ufw Breaks
# its package on noble); instead a oneshot systemd unit ordered After=docker.service
# replays a helper script. The helper reads the IRC gate from a state file, so
# re-running this script with IRC_ENABLED=true is honoured on the next boot too.
mkdir -p /etc/korin
echo "${IRC_ENABLED}" >/etc/korin/irc_enabled

install -m 0755 /dev/stdin /usr/local/sbin/korin-docker-user.sh <<'KORINFW'
#!/usr/bin/env bash
# GENERATED by packages/harden - replays the DOCKER-USER perimeter after docker
# recreates the chain. Reads the IRC gate written by the harden script.
set -euo pipefail
IRC_ENABLED="$(cat /etc/korin/irc_enabled 2>/dev/null || echo false)"
# Flush first: the chain ships with a default "-j RETURN", so appended DROPs
# would never be reached otherwise.
iptables -F DOCKER-USER 2>/dev/null || true
iptables -A DOCKER-USER -m conntrack --ctstate ESTABLISHED,RELATED -j RETURN
if [ "$IRC_ENABLED" = "true" ]; then
  iptables -A DOCKER-USER -p tcp --dport 6697 -m conntrack --ctstate NEW -m hashlimit --hashlimit-name irc6697 --hashlimit-mode srcip --hashlimit-above 30/min --hashlimit-burst 30 -j DROP
  iptables -A DOCKER-USER -p tcp --dport 6697 -m connlimit --connlimit-above 8 --connlimit-mask 32 -j DROP
  iptables -A DOCKER-USER -p tcp --dport 6697 -j RETURN
  iptables -A DOCKER-USER -p tcp --dport 8097 -m conntrack --ctstate NEW -m hashlimit --hashlimit-name irc8097 --hashlimit-mode srcip --hashlimit-above 30/min --hashlimit-burst 30 -j DROP
  iptables -A DOCKER-USER -p tcp --dport 8097 -m connlimit --connlimit-above 8 --connlimit-mask 32 -j DROP
  iptables -A DOCKER-USER -p tcp --dport 8097 -j RETURN
  iptables -A DOCKER-USER -p tcp --dport 6667 -m conntrack --ctstate NEW -m hashlimit --hashlimit-name irc6667 --hashlimit-mode srcip --hashlimit-above 30/min --hashlimit-burst 30 -j DROP
  iptables -A DOCKER-USER -p tcp --dport 6667 -m connlimit --connlimit-above 8 --connlimit-mask 32 -j DROP
  iptables -A DOCKER-USER -p tcp --dport 6667 -j RETURN
fi
iptables -A DOCKER-USER -j DROP
KORINFW

cat >/etc/systemd/system/korin-docker-user.service <<'KORINUNIT'
[Unit]
Description=Re-apply korin.pink DOCKER-USER firewall rules
After=docker.service
Requires=docker.service

[Service]
Type=oneshot
ExecStart=/usr/local/sbin/korin-docker-user.sh

[Install]
WantedBy=multi-user.target
KORINUNIT
systemctl daemon-reload
systemctl enable korin-docker-user.service
# Apply now - docker is already up from the apt install above.
/usr/local/sbin/korin-docker-user.sh

# -- fail2ban ----------------------------------------------------------------
mkdir -p /etc/fail2ban/jail.d
cat >/etc/fail2ban/jail.d/korin.local <<'JAIL'
[sshd]
enabled  = true
maxretry = 4
bantime  = 1h
JAIL

# The [ergo] jail is added only once IRC is live, so fail2ban never references a
# missing logpath (which would error the jail at first boot).
if [ "$IRC_ENABLED" = "true" ]; then
  cat >/etc/fail2ban/filter.d/ergo.conf <<'FILTER'
[Definition]
failregex = ^.*failed login.*?<HOST>
            ^.*rejecting connection.*?<HOST>
            ^.*too many connections.*?<HOST>
ignoreregex =
FILTER
  mkdir -p "$(dirname /opt/korin.pink/infra/ergo-data/ergo.log)"
  touch "/opt/korin.pink/infra/ergo-data/ergo.log"
  cat >>/etc/fail2ban/jail.d/korin.local <<'JAIL'

[ergo]
enabled  = true
filter   = ergo
logpath  = /opt/korin.pink/infra/ergo-data/ergo.log
maxretry = 6
findtime = 5m
bantime  = 1h
JAIL
fi
systemctl enable --now fail2ban
systemctl restart fail2ban || true

echo "[korin] hardening applied. IRC_ENABLED=${IRC_ENABLED}."
echo "[korin] After Ergo is live, re-run with IRC_ENABLED=true to open the IRC ports."
