// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  ircSidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Home',
    },
    {
      type: 'category',
      label: 'IRC',
      collapsed: false,
      items: [
        'irc/irc-index',
        'irc/irc-connecting',
        'irc/irc-channels',
        'irc/irc-etiquette',
        'irc/irc-score',
      ],
    },
  ],

  archiveSidebar: [
    {
      type: 'category',
      label: 'Code Noobs Archive',
      collapsed: false,
      items: [
        'code-noobs-archive/index',
        'code-noobs-archive/Introduction to Programming',
        'code-noobs-archive/Introduction to DOM',
        'code-noobs-archive/Functions',
        'code-noobs-archive/Promises',
      ],
    },
    {
      type: 'category',
      label: 'Audio & Gear',
      items: [
        'audiophile',
        'Stereo-Setup',
        'Sapphire-Zen-Build',
      ],
    },
    {
      type: 'category',
      label: 'Operating Systems',
      items: [
        { type: 'autogenerated', dirName: 'operating-system' },
      ],
    },
  ],
};

export default sidebars;
