// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // One site-wide sidebar so IRC and Code Noobs sit at equal depth and are both
  // visible from every page (previously they lived in separate sidebars and
  // never appeared together).
  mainSidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Home',
    },
    {
      type: 'category',
      label: 'IRC',
      collapsed: false,
      items: [
        'irc/irc-index',
        'irc/irc-connecting',
        'irc/irc-channels',
        'irc/irc-etiquette',
        'irc/irc-score',
      ],
    },
    {
      type: 'category',
      label: 'Code Noobs',
      collapsed: false,
      items: [
        { type: 'doc', id: 'code-noobs-archive/index', label: 'Code Noobs Root' },
        'code-noobs-archive/Introduction to Programming',
        'code-noobs-archive/Introduction to DOM',
        'code-noobs-archive/Functions',
        'code-noobs-archive/Promises',
        'code-noobs-archive/App Project',
        'code-noobs-archive/Whisklist Proof of Concept',
        'code-noobs-archive/Building a PC',
        'code-noobs-archive/Linux Free Open Source Software 101',
        'code-noobs-archive/Stencil CLI and Postman',
        'code-noobs-archive/2018 Year in Review',
      ],
    },
    {
      type: 'category',
      label: 'Audio & Gear',
      items: [
        'audiophile',
        'Stereo-Setup',
        'Sapphire-Zen-Build',
      ],
    },
    {
      type: 'category',
      label: 'Enthusiast',
      items: [
        'cinephile',
        'eJuice-Supplies&-Tips',
      ],
    },
    {
      type: 'category',
      label: 'Operating Systems',
      items: [
        { type: 'autogenerated', dirName: 'operating-system' },
      ],
    },
    {
      type: 'category',
      label: 'Blog Posts',
      items: [
        { type: 'autogenerated', dirName: 'blog-posts' },
      ],
    },
    {
      type: 'category',
      label: 'Streaming',
      items: [
        'strem/index',
        'strem/VoD-Prod',
      ],
    },
    {
      type: 'category',
      label: 'Japanese',
      items: [
        'JP/index',
        'JP/五大',
      ],
    },
    {
      type: 'category',
      label: 'Lineage (legacy)',
      items: [
        'Contributor-Program',
        'Privacy-Policy',
        'GitLab-Public-Docs',
        'Digital-Nomad-Integration',
      ],
    },
    {
      type: 'category',
      label: 'Misc',
      items: [
        'dream-journal',
        'ascii-art',
        'DevOps/nginx',
        'license',
      ],
    },
  ],
};

export default sidebars;
