import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { fail2banFailregex } from './fail2ban.js';
import { buildStartupScript } from './startup.js';

// packages/harden/src -> repo root
const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../../..');

const IRC_PORTS = [6697, 8097, 6667];
const LIMITS = { newConnsPerMinPerIp: 30, maxConcurrentPerIp: 8 };
const ERGO_LOG = '/opt/korin.pink/infra/ergo-data/ergo.log';
const PUBLIC_IFACE = 'eth0'; // Vultr Ubuntu egress NIC
const WEB_PORTS = [80, 443]; // front-door Caddy (api.korin.pink)

const startup = buildStartupScript({
  ircPorts: IRC_PORTS,
  limits: LIMITS,
  ergoLog: ERGO_LOG,
  publicIface: PUBLIC_IFACE,
  webPorts: WEB_PORTS,
});

const failregex = fail2banFailregex();
const filter = `# GENERATED by packages/harden - reference copy of the embedded fail2ban filter.
# The startup script writes this to /etc/fail2ban/filter.d/ergo.conf itself.
# Validate against real Ergo logs before trusting it (log strings vary by version).
[Definition]
failregex = ${failregex.join('\n            ')}
ignoreregex =
`;

mkdirSync(resolve(repo, 'infra/fail2ban'), { recursive: true });
writeFileSync(resolve(repo, 'infra/vultr-startup.sh'), startup);
writeFileSync(resolve(repo, 'infra/fail2ban/ergo.conf'), filter);
console.log('rendered: infra/vultr-startup.sh, infra/fail2ban/ergo.conf');
