import { writeFileSync, mkdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { buildFirewallRules, buildIrcPortRules } from './firewall.js';
import { fail2banFailregex } from './fail2ban.js';

// packages/harden/src -> repo root
const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, '../../..');

const IRC_PORTS = [6697, 8097, 6667];
const LIMITS = { newConnsPerMinPerIp: 30, maxConcurrentPerIp: 8 };
const ERGO_LOG = '/opt/korin.pink/infra/ergo-data/ergo.log';

// Framing rules (established RETURN first, default DROP last); the IRC port
// rules sit between them but are applied at RUNTIME, gated by $IRC_ENABLED, so
// re-running with IRC_ENABLED=true actually opens + rate-limits the ports.
const framing = buildFirewallRules({
  sshAllowCidr: '',
  ircEnabled: false,
  ircPorts: IRC_PORTS,
  ...LIMITS,
});
const established = framing[0];
const defaultDrop = framing[framing.length - 1];
const ircRules = buildIrcPortRules(IRC_PORTS, LIMITS);
const failregex = fail2banFailregex();

const startup = `#!/usr/bin/env bash
# GENERATED by packages/harden (pnpm --filter @korin/harden render). Do not edit by hand.
# Vultr "Startup Script" (Boot Script): free abuse/flood hardening for korin.pink.
# Self-contained - does not require the repo to be cloned. Idempotent; safe to re-run.
# Volumetric L3/4 DDoS still needs upstream scrubbing - see docs/deploy/vps.md.
set -euo pipefail

# REQUIRED: lock SSH to your admin IP. Leaving 0.0.0.0/0 exposes SSH to the world.
# Vultr Boot Scripts do not inject env vars - set these inline before deploying.
SSH_ALLOW_CIDR="\${SSH_ALLOW_CIDR:-0.0.0.0/0}"
# Flip to "true" once Ergo is live, then re-run, to open + rate-limit the IRC ports.
IRC_ENABLED="\${IRC_ENABLED:-false}"

export DEBIAN_FRONTEND=noninteractive
apt-get update
apt-get install -y docker.io docker-compose-v2 ufw fail2ban netfilter-persistent iptables-persistent

# -- Host firewall (ufw) -----------------------------------------------------
# NOTE: Docker-published ports BYPASS ufw - the IRC ports are filtered in the
# DOCKER-USER chain below, not here.
ufw default deny incoming
ufw default allow outgoing
ufw allow from "\${SSH_ALLOW_CIDR}" to any port 22 proto tcp
ufw allow 80/tcp
ufw allow 443
ufw --force enable

# -- Kernel hardening (small SYN-flood resistance) ---------------------------
cat >/etc/sysctl.d/99-korin-harden.conf <<'SYSCTL'
net.ipv4.tcp_syncookies = 1
net.ipv4.tcp_max_syn_backlog = 4096
net.core.somaxconn = 1024
net.ipv4.conf.all.rp_filter = 1
SYSCTL
sysctl --system

# -- SSH lockdown (key-only) - make sure your key is attached at deploy! ------
sed -i 's/^#\\?PasswordAuthentication.*/PasswordAuthentication no/' /etc/ssh/sshd_config
sed -i 's/^#\\?PermitRootLogin.*/PermitRootLogin prohibit-password/' /etc/ssh/sshd_config
systemctl reload ssh 2>/dev/null || systemctl reload sshd 2>/dev/null || true

# -- DOCKER-USER perimeter (the real filter for published IRC ports) ---------
# Flush first: the chain ships with a default "-j RETURN", so appended DROPs
# would never be reached otherwise.
iptables -F DOCKER-USER 2>/dev/null || true
${established}
if [ "\$IRC_ENABLED" = "true" ]; then
${ircRules.map((r) => '  ' + r).join('\n')}
fi
${defaultDrop}
netfilter-persistent save || true

# -- fail2ban ----------------------------------------------------------------
mkdir -p /etc/fail2ban/jail.d
cat >/etc/fail2ban/jail.d/korin.local <<'JAIL'
[sshd]
enabled  = true
maxretry = 4
bantime  = 1h
JAIL

# The [ergo] jail is added only once IRC is live, so fail2ban never references a
# missing logpath (which would error the jail at first boot).
if [ "\$IRC_ENABLED" = "true" ]; then
  cat >/etc/fail2ban/filter.d/ergo.conf <<'FILTER'
[Definition]
failregex = ${failregex.join('\n            ')}
ignoreregex =
FILTER
  mkdir -p "$(dirname ${ERGO_LOG})"
  touch "${ERGO_LOG}"
  cat >>/etc/fail2ban/jail.d/korin.local <<'JAIL'

[ergo]
enabled  = true
filter   = ergo
logpath  = ${ERGO_LOG}
maxretry = 6
findtime = 5m
bantime  = 1h
JAIL
fi
systemctl enable --now fail2ban
systemctl restart fail2ban || true

echo "[korin] hardening applied. IRC_ENABLED=\${IRC_ENABLED}."
echo "[korin] After Ergo is live, re-run with IRC_ENABLED=true to open the IRC ports."
`;

const filter = `# GENERATED by packages/harden - reference copy of the embedded fail2ban filter.
# The startup script writes this to /etc/fail2ban/filter.d/ergo.conf itself.
# Validate against real Ergo logs before trusting it (log strings vary by version).
[Definition]
failregex = ${failregex.join('\n            ')}
ignoreregex =
`;

mkdirSync(resolve(repo, 'infra/fail2ban'), { recursive: true });
writeFileSync(resolve(repo, 'infra/vultr-startup.sh'), startup);
writeFileSync(resolve(repo, 'infra/fail2ban/ergo.conf'), filter);
console.log('rendered: infra/vultr-startup.sh, infra/fail2ban/ergo.conf');
